#!/bin/sh
/usr/sbin/service privoxy1 restart
/usr/sbin/service privoxy2 restart
/usr/sbin/service privoxy3 restart
/usr/sbin/service privoxy4 restart
/usr/sbin/service privoxy5 restart
/usr/sbin/service privoxy6 restart
/usr/sbin/service privoxy7 restart
/usr/sbin/service privoxy8 restart
/usr/sbin/service privoxy9 restart
/usr/sbin/service privoxy10 restart
/usr/sbin/service privoxy11 restart
/usr/sbin/service privoxy12 restart
/usr/sbin/service privoxy13 restart
/usr/sbin/service privoxy14 restart
/usr/sbin/service privoxy15 restart
/usr/sbin/service privoxy16 restart
/usr/sbin/service privoxy17 restart
/usr/sbin/service privoxy18 restart
/usr/sbin/service privoxy19 restart
/usr/sbin/service privoxy20 restart
/usr/sbin/service privoxy21 restart
/usr/sbin/service privoxy22 restart
/usr/sbin/service privoxy23 restart
/usr/sbin/service privoxy24 restart